(function(){var g=this&&this.Pa||function(){var b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return function(c,a){function d(){this.constructor=c}b(c,a);c.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)}}(),h;
(function(b){(function(c){var a;(function(a){a[a.A=65]="A";a[a.D=68]="D";a[a.W=87]="W";a[a.S=83]="S";a[a.LEFT=37]="LEFT";a[a.RIGHT=39]="RIGHT";a[a.UP=38]="UP";a[a.DOWN=40]="DOWN";a[a.ENTER=13]="ENTER";a[a.SPACE=32]="SPACE";a[a.NUM_1=49]="NUM_1";a[a.NUM_2=50]="NUM_2";a[a.NUM_3=51]="NUM_3";a[a.NUM_4=52]="NUM_4";a[a.NUM_5=53]="NUM_5";a[a.C=67]="C"})(a=c.ea||(c.ea={}));var b;(function(a){a[a.UP=0]="UP";a[a.DOWN=1]="DOWN";a[a.LEFT=2]="LEFT";a[a.RIGHT=3]="RIGHT";a[a.ACTION=4]="ACTION"})(b=c.s||(c.s={}));
c.j=[];c.j[b.R]=[a.Oa,a.R];c.j[b.Y]=[a.Ia,a.Y];c.j[b.fa]=[a.Ca,a.fa];c.j[b.ga]=[a.Ea,a.ga];c.j[b.X]=[a.Ja,a.Fa];var f=[],k=[],e=[];for(a=0;256>a;a++)k[a]=!0;c.Sa=function(a){return f[a]};c.Va=function(a){var c=e[a];e[a]=!1;return c};c.Qa=function(){for(var a in e)e[a]=!1};c.sa=function(a){a=a.which;f[a]=!0;k[a]&&(e[a]=!0);k[a]=!1};c.ta=function(a){a=a.which;f[a]=!1;k[a]=!0};c.Ra=function(a){var b=!1,d=0;for(a=c.j[a];d<a.length;d++)var k=a[d],b=b||f[k];return b};c.H=function(a){var b=!1,d=0;for(a=
c.j[a];d<a.length;d++){var f=a[d],b=b||e[f];e[f]=!1}return b}})(b.b||(b.b={}))})(h||(h={}));
var r=function(){function b(c,a,b){this.w=a;this.B=c;this.ha=b;l.P.add("sheet","./sheet.png");l.P.load(this.ra.bind(this))}b.prototype.ra=function(){this.f=new m(this.w);this.la();this.f.c.register("main-menu",new n(this));this.f.c.register("game-screen",new p(this));this.f.c.push("main-menu");this.f.wa()};b.prototype.la=function(){this.B.addEventListener("resize",this.ba.bind(this),!1);this.ba();this.B.onkeydown=h.b.sa;this.B.onkeyup=h.b.ta;this.B.onblur=this.f.pause.bind(this.f);this.B.onfocus=
this.f.Aa.bind(this.f);this.ja=new q(this.ha)};b.prototype.ba=function(){var c=Math.min(window.innerWidth/this.w.width,window.innerHeight/this.w.height)|0,c=0>=c?1:c,a=[this.w.width*c,this.w.height*c],b=[(window.innerWidth-a[0])/2,(window.innerHeight-a[1])/2],a=document.getElementById("stage"),c="translate("+~~b[0]+"px, "+~~b[1]+"px) scale("+~~c+")";a.style.transform=c;a.style.webkitTransform=c};return b}(),t=r||(r={});t.h=512;t.o=288;t.Ma=8;
var u=function(){function b(c){this.U=c;this.a=!0;this.l=!1}b.prototype.m=function(){this.a=!0;this.update(0)};b.prototype.G=function(){this.a=!0;this.update(0)};return b}(),v=function(){function b(){this.da={};this.N=[]}b.prototype.register=function(c,a){this.da[c]=a};Object.defineProperty(b.prototype,"current",{get:function(){return this.N[this.N.length-1]},enumerable:!0,configurable:!0});b.prototype.push=function(c){this.current&&this.current.G();this.N.push(this.da[c]);this.current&&this.current.m()};
b.prototype.pop=function(){this.current&&this.current.G();this.N.pop();this.current&&this.current.m()};return b}(),m=function(){function b(c){this.F=this.a=this.T=!1;this.screen=c;this.i=this.screen.getContext("2d");this.i.va=!1;this.i.qa=!1;this.buffer=document.createElement("canvas");this.buffer.width=this.screen.width;this.buffer.height=this.screen.height;this.J=this.buffer.getContext("2d");this.J.va=!1;this.J.qa=!1;this.c=new v}b.prototype.update=function(c){this.F||this.c.current.update(c)};
b.prototype.K=function(){if(this.T||this.c.current.l)this.i.clearRect(0,0,this.screen.width,this.screen.height),this.J.clearRect(0,0,this.screen.width,this.screen.height),this.T=this.c.current.l=!1;this.F||!this.a&&!this.c.current.a?this.F&&this.a&&(this.i.globalAlpha=.7,this.i.fillStyle="black",this.i.fillRect(0,0,r.h,r.o),this.i.globalAlpha=1,this.a=this.c.current.a=!1):(this.c.current.K(this.J),this.i.drawImage(this.buffer,0,0,r.h,r.o,0,0,r.h,r.o),this.a=this.c.current.a=!1)};b.prototype.loop=
function(){var c=window.performance.now(),a=c-this.then;this.then=c;this.update(a);this.K();this.aa=window.requestAnimationFrame(this.loop.bind(this))};b.prototype.wa=function(){this.aa=window.requestAnimationFrame(this.loop.bind(this))};b.prototype.stop=function(){window.cancelAnimationFrame(this.aa)};b.prototype.pause=function(){this.a=this.F=!0};b.prototype.Aa=function(){this.F=!1;this.c.current.a=this.T=!0};return b}(),q=function(){function b(c){this.ia=c}b.prototype.ka=function(){var c=new w,
a=this.ia,b=a.createOscillator(),f=a.createGain(),k=c.Ba||1;b.type=c.shape;b.frequency.setValueAtTime(c.Z,a.currentTime);b.frequency.exponentialRampToValueAtTime(c.oa,a.currentTime+c.L/2);b.frequency.exponentialRampToValueAtTime(c.Z,a.currentTime+c.L);f.gain.setValueAtTime(k,a.currentTime);f.gain.exponentialRampToValueAtTime(.001,a.currentTime+c.L);b.connect(f);f.connect(a.destination);b.start(a.currentTime);b.stop(a.currentTime+c.L)};return b}();
function w(){this.Z=300;this.oa=2E3;this.shape="square";this.Ba=this.L=1}function x(b){this.name=b}var y=function(){function b(c,a){void 0===c&&(c=0);void 0===a&&(a=0);this.O=c;this.M=a}b.I=function(c,a){return new b(c,a)};return b}(),z=function(){function b(c,a){void 0===c&&(c=0);void 0===a&&(a=0);this.x=c;this.y=a}b.I=function(c,a){return new b(c,a)};return b}(),A;
(function(b){var c=function(a){function c(b){var d=b.O,d=void 0===d?0:d;b=b.M;b=void 0===b?0:b;var e=a.call(this,"aabb")||this;e.value=new y(d,b);return e}g(c,a);return c}(x);b.Da=c;c=function(a){function c(b){var d=b.x,d=void 0===d?0:d;b=b.y;b=void 0===b?0:b;var e=a.call(this,"position")||this;e.value=new z(d,b);return e}g(c,a);return c}(x);b.Ha=c;c=function(a){function c(b){var d=a.call(this,"style")||this;d.value=b;return d}g(c,a);return c}(x);b.La=c;c=function(a){function c(b){var d=a.call(this,
"sprite")||this;d.value=b;return d}g(c,a);return c}(x);b.Ka=c;c=function(a){function c(b,d){var e=a.call(this,b)||this;e.value=d;return e}g(c,a);return c}(x);b.Na=c;c=function(a){function c(b,d){var e=a.call(this,b)||this;e.value=d;return e}g(c,a);return c}(x);b.Ga=c})(A||(A={}));(function(){function b(){b.I||(b.I=0);this.id=b.I++;return this}return b})();var l;
(function(b){var c={};b.pa=function(a){return c[a]};var a={},d=0;(function(b){b.add=function(c,b){a[c]=b;d++};b.load=function(b){function e(a){a.na++===a.ua&&a.ma()}b={na:0,ua:0,ma:b};for(var f in a)c[f]=new Image,c[f].src=a[f],c[f].onload=e.bind(this,b),delete a[f];d=0}})(b.P||(b.P={}))})(l||(l={}));
(function(){function b(c,a,b,f,k,e){void 0===f&&(f=0);void 0===k&&(k=new y(0,0));void 0===e&&(e=new z(0,0));this.xa=[];this.name=a;this.offset=e;this.v=k;this.g=b;this.$=f;this.V=l.pa(c);this.za()}b.prototype.za=function(){this.ca=0===this.v.O||0===this.v.M?this.V.width/this.g:this.v.O;this.ya=0===this.v.O||0===this.v.M?this.V.height/this.g:this.v.M;for(var b,a=0;a<this.ya;a++)for(var d=0;d<this.ca;d++)b=this.xa[d+a*this.ca]=document.createElement("canvas"),b.width=this.g,b.height=this.g,b.getContext("2d").drawImage(this.V,
(this.g+this.$)*d+this.offset.x,(this.g+this.$)*a+this.offset.y,this.g,this.g,0,0,this.g,this.g)};return b})();var B;(function(b){var c={};b.Ua=function(a){c[a.name]=a};b.Ta=function(a){return c[a]}})(B||(B={}));
var p=function(b){function c(a){return b.call(this,a)||this}g(c,b);c.prototype.m=function(){this.l=!0;b.prototype.m.call(this)};c.prototype.G=function(){b.prototype.G.call(this)};c.prototype.update=function(){h.b.H(h.b.s.X)&&this.U.f.c.pop();h.b.H(h.b.s.R)&&this.U.ja.ka()};c.prototype.K=function(a){this.a&&(a.globalAlpha=1,a.fillStyle="blue",a.fillRect(0,0,~~r.h,~~r.o),a.globalAlpha=.75,a.textAlign="center",a.fillStyle=a.strokeStyle="yellow",a.lineWidth=2,a.fillText("This is the game screen, baby.",
~~(r.h/2|0),64))};return c}(u),n=function(b){function c(a){a=b.call(this,a)||this;a.selectedIndex=0;a.u=["Start","Options","Exit"];return a}g(c,b);c.prototype.m=function(){this.l=!0;b.prototype.m.call(this)};c.prototype.G=function(){this.l=!0;b.prototype.m.call(this)};c.prototype.update=function(){if(h.b.H(h.b.s.X))switch(this.selectedIndex){case 0:this.U.f.c.push("game-screen");break;case 1:break;default:window.location.reload()}h.b.H(h.b.s.Y)&&(this.selectedIndex=(this.selectedIndex+1)%this.u.length,
this.a=this.l=!0);h.b.H(h.b.s.R)&&(this.selectedIndex=0===this.selectedIndex?this.u.length-1:(this.selectedIndex-1)%3,this.a=this.l=!0)};c.prototype.K=function(a){if(this.a){a.globalAlpha=1;a.font="18px Verdana";a.textAlign="center";a.fillStyle=a.strokeStyle="black";a.lineWidth=2;a.fillText("js13k 2017",~~(r.h/2|0),64);for(var b=0;b<this.u.length;b++)a.fillText(this.u[b],~~(r.h/2|0),~~((r.o|0)-36*this.u.length+36*b));a.strokeRect(~~(r.h/2-75),~~(r.o-36*this.u.length+36*this.selectedIndex-18),150,
24)}};return c}(u);}).call(window);
